trigger:
- main

pool: MichiPC

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'SWKOM'
    definition: 'Main CI'
    buildVersionToDownload: 'latest'
    artifactName: 'Paperless'
    targetPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(cdf4ea9a-0027-4678-aee6-c9dbcc54a1ea)'
    appType: 'webApp'
    WebAppName: 'PaperlessSWKOM'
    deployToSlotOrASE: true
    ResourceGroupName: 'Paperless'
    SlotName: 'production'
    Package: '$(System.ArtifactsDirectory)/WebApp.zip'
    enableCustomDeployment: true
