trigger:
- main

pool: MichiPC

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifact: 'Paperless'
    targetPath: '$(System.ArtifactsDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(cdf4ea9a-0027-4678-aee6-c9dbcc54a1ea)'
    appType: 'webApp'
    appName: 'PaperlessSWKOM'
    deployToSlotOrASE: true
    resourceGroupName: 'Paperless'
    slotName: 'production'
    package: '$(System.ArtifactsDirectory)/Paperless/WebApp.zip'
    deploymentMethod: 'auto'
    appSettings:
