trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'SWKOM'
    definition: 'Main CI'
    buildVersionToDownload: 'latest'
    artifactName: 'Paperless'
    targetPath: '$(System.ArtifactsDirectory)'

- powershell: |
    $zipPath = "$(System.ArtifactsDirectory)\WebApp.zip"
    $extractPath = "$(System.ArtifactsDirectory)\Extracted"
    Expand-Archive -Path $zipPath -DestinationPath $extractPath
  displayName: 'Unzip WebApp.zip'

- powershell: |
    $sourcePath = '$(System.ArtifactsDirectory)\Extracted\Content\D_C\a\1\s\Paperless\obj\Release\net7.0\PubTmp\Out'
    $destPath = '$(System.ArtifactsDirectory)\Test'
    Copy-Item -Path $sourcePath -Destination $destPath -Recurse -Force
  displayName: 'Copy Files from Source to Destination'

- powershell: |
    $sourceDirectory = "$(System.ArtifactsDirectory)\Test"
    $destinationZipFile = "$(System.ArtifactsDirectory)\WebApp.zip"
    Add-Type -Assembly "System.IO.Compression.FileSystem"
    [System.IO.Compression.ZipFile]::CreateFromDirectory($sourceDirectory, $destinationZipFile)
  displayName: 'Rezip lol'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(cdf4ea9a-0027-4678-aee6-c9dbcc54a1ea)'
    appType: 'webAppLinux'
    WebAppName: 'Paperlessswkom'
    deployToSlotOrASE: true
    ResourceGroupName: 'Paperless'
    SlotName: 'production'
    packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|7.0'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'