# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  webserver:
    build:
      context: ./PaperlessServer
      dockerfile: Paperless.frontend/Dockerfile
    depends_on:
      - rest
    ports:
      - "8080:80"
    networks:
      - paperlessnetwork

  rest:
    build:
      context: ./PaperlessServer
      dockerfile: Paperless.rest/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - paperlessnetwork

  services:
    build:
      context: ./PaperlessServer
      dockerfile: Paperless.services/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - paperlessnetwork
  
  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - paperlessnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - paperlessnetwork
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - paperlessnetwork

volumes:
  data:
  media:
  pgdata:

networks:
  paperlessnetwork:
    driver: bridge